import { UserNovel } from './shared/models/UserNovel';

export const LOGIN_MODES: Array<string> = ['Basic', 'Auth'];

export const USER_PERMISSIONS: Array<string> = ['listread', 'listwrite'];

export enum VN_RELEASE_STATUS {
  'Unknown',
  'Pending',
  'Obtained',
  'On Loan',
  'Deleted',
}

export const VN_PROPS: Array<string> = [
  'vn.id',
  'vn.title',
  'vn.alttitle',
  'vn.titles.lang',
  'vn.titles.title',
  'vn.titles.latin',
  'vn.titles.official',
  'vn.titles.main',
  'vn.aliases',
  'vn.olang',
  'vn.devstatus',
  'vn.released',
  'vn.languages',
  'vn.platforms',
  'vn.image.id',
  'vn.image.url',
  'vn.image.dims',
  'vn.image.sexual',
  'vn.image.violence',
  'vn.image.votecount',
  'vn.length',
  'vn.length_minutes',
  'vn.length_votes',
  'vn.description',
  'vn.rating',
  'vn.popularity',
  'vn.votecount',
  'vn.screenshots.thumbnail',
  'vn.screenshots.thumbnail_dims',
  'vn.tags.rating',
  'vn.tags.spoiler',
  'vn.tags.lie',
];

export const ULIST_PROPS: Array<string> = [
  // User Novel Stuff
  'id',
  'added',
  'voted',
  'lastmod',
  'vote',
  'started',
  'finished',
  'notes',

  // Visual Novel Stuff
  ...VN_PROPS,
];

export const SAMPLE_NOVEL: UserNovel = {
  finished: null,
  id: 'v24',
  started: null,
  vote: 90,
  voted: 1634273062,
  added: 1569731921,
  lastmod: 1665840699,
  notes: 'when 6 people die in a single night but the soundtrack is bumpin',
  vn: {
    image: {
      dims: [256, 361],
      votecount: 12,
      url: 'https://s2.vndb.org/cv/76/26976.jpg',
      id: 'cv26976',
      sexual: 0,
      violence: 0,
    },
    length: 5,
    description:
      "Umineko no Naku Koro ni takes place in 1986 on October 4 and 5 on a secluded island called Rokkenjima (六軒島). The head of a wealthy family named [url=/c200]Ushiromiya Kinzou[/url], who lives on and owns Rokkenjima, is near death, and eleven of his family members arrive on the island to discuss how Kinzou's assets will be divided once he is dead. Also on the island are five of Kinzou's servants and his physician. After the eleven family members arrive, a typhoon traps them on the island and shortly after, people get mysteriously murdered.\n\n[Edited from [url=http://witch-hunt.com/]The Witch Hunt[/url]]",
    released: '2007-08-17',
    alttitle: 'うみねこのなく頃に',
    devstatus: 0,
    length_votes: 334,
    votecount: 9154,
    length_minutes: 4560,
    titles: [
      {
        lang: 'en',
        title: 'Umineko When They Cry - Question Arcs',
        main: false,
        latin: null,
        official: true,
      },
      {
        lang: 'ja',
        title: 'うみねこのなく頃に',
        main: true,
        latin: 'Umineko no Naku Koro ni',
        official: true,
      },
      {
        lang: 'ru',
        title: 'Когда плачут чайки',
        main: false,
        latin: null,
        official: true,
      },
      {
        title: '海猫鸣泣之时',
        main: false,
        lang: 'zh-Hans',
        official: false,
        latin: 'Haimao Mingqi zhi Shi',
      },
    ],
    olang: 'ja',
    platforms: [
      'win',
      'lin',
      'mac',
      'ios',
      'and',
      'psp',
      'ps3',
      'ps4',
      'swi',
      'vnd',
      'web',
    ],
    aliases: ['When They Cry 3', 'When The Seagulls Cry'],
    tags: [
      {
        spoiler: 0,
        id: 'g2967',
        lie: false,
        rating: 2,
      },
      {
        spoiler: 1,
        rating: 1.25,
        id: 'g580',
        lie: false,
      },
      {
        id: 'g1431',
        lie: false,
        rating: 2.8181818,
        spoiler: 1,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g676',
        rating: 1.9,
      },
      {
        rating: 2.5555556,
        lie: false,
        id: 'g133',
        spoiler: 0,
      },
      {
        rating: 2.392857,
        id: 'g218',
        lie: false,
        spoiler: 0,
      },
      {
        rating: 2.2307692,
        lie: false,
        id: 'g1004',
        spoiler: 1,
      },
      {
        lie: false,
        id: 'g902',
        rating: 1.4,
        spoiler: 0,
      },
      {
        lie: false,
        id: 'g709',
        rating: 2.9268293,
        spoiler: 0,
      },
      {
        spoiler: 0,
        rating: 2.675,
        lie: false,
        id: 'g145',
      },
      {
        spoiler: 2,
        lie: false,
        id: 'g333',
        rating: 3,
      },
      {
        id: 'g617',
        lie: false,
        rating: 3,
        spoiler: 0,
      },
      {
        rating: 2.5641026,
        lie: false,
        id: 'g157',
        spoiler: 0,
      },
      {
        lie: false,
        id: 'g136',
        rating: 2.2432432,
        spoiler: 0,
      },
      {
        id: 'g1173',
        lie: false,
        rating: 2.2333333,
        spoiler: 0,
      },
      {
        spoiler: 0,
        id: 'g2071',
        lie: false,
        rating: 2,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g43',
        rating: 2.878049,
      },
      {
        lie: false,
        id: 'g488',
        rating: 2.75,
        spoiler: 1,
      },
      {
        rating: 2.2857144,
        lie: false,
        id: 'g795',
        spoiler: 0,
      },
      {
        rating: 2.8043478,
        lie: false,
        id: 'g293',
        spoiler: 1,
      },
      {
        rating: 2.55,
        lie: false,
        id: 'g741',
        spoiler: 0,
      },
      {
        spoiler: 0,
        rating: 1.3888888,
        id: 'g1624',
        lie: false,
      },
      {
        spoiler: 0,
        rating: 3,
        lie: false,
        id: 'g2616',
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g1299',
        rating: 1.5909091,
      },
      {
        rating: 2.7631578,
        id: 'g728',
        lie: false,
        spoiler: 0,
      },
      {
        rating: 2.6,
        lie: false,
        id: 'g789',
        spoiler: 0,
      },
      {
        rating: 1.6944444,
        lie: false,
        id: 'g63',
        spoiler: 1,
      },
      {
        spoiler: 2,
        rating: 2.0769231,
        id: 'g1252',
        lie: false,
      },
      {
        rating: 2.7586207,
        lie: false,
        id: 'g1001',
        spoiler: 2,
      },
      {
        spoiler: 0,
        rating: 3,
        lie: false,
        id: 'g325',
      },
      {
        rating: 2.974359,
        id: 'g779',
        lie: false,
        spoiler: 2,
      },
      {
        rating: 2.2432432,
        lie: false,
        id: 'g691',
        spoiler: 2,
      },
      {
        spoiler: 0,
        id: 'g158',
        lie: false,
        rating: 1.0526316,
      },
      {
        spoiler: 1,
        rating: 2.0277777,
        id: 'g80',
        lie: false,
      },
      {
        rating: 0.44444445,
        lie: false,
        id: 'g2150',
        spoiler: 2,
      },
      {
        rating: 2.7727273,
        lie: false,
        id: 'g4',
        spoiler: 1,
      },
      {
        rating: 2.7058823,
        lie: false,
        id: 'g1889',
        spoiler: 0,
      },
      {
        spoiler: 2,
        lie: false,
        id: 'g250',
        rating: 2.5681818,
      },
      {
        spoiler: 0,
        id: 'g614',
        lie: false,
        rating: 1,
      },
      {
        rating: 3,
        lie: false,
        id: 'g153',
        spoiler: 0,
      },
      {
        rating: 1.3181819,
        lie: false,
        id: 'g164',
        spoiler: 1,
      },
      {
        rating: 2.425,
        lie: false,
        id: 'g147',
        spoiler: 0,
      },
      {
        rating: 1.125,
        lie: false,
        id: 'g1195',
        spoiler: 0,
      },
      {
        spoiler: 1,
        rating: 1.5945946,
        lie: false,
        id: 'g36',
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g2440',
        rating: 1.75,
      },
      {
        spoiler: 0,
        rating: 3,
        id: 'g3608',
        lie: false,
      },
      {
        lie: false,
        id: 'g8',
        rating: 2.6341465,
        spoiler: 1,
      },
      {
        spoiler: 0,
        id: 'g469',
        lie: false,
        rating: 2.0232558,
      },
      {
        spoiler: 2,
        lie: false,
        id: 'g481',
        rating: 2.5,
      },
      {
        spoiler: 0,
        rating: 1.625,
        id: 'g373',
        lie: false,
      },
      {
        spoiler: 0,
        rating: 2.6666667,
        id: 'g873',
        lie: false,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g1246',
        rating: 2.3181818,
      },
      {
        spoiler: 0,
        id: 'g309',
        lie: false,
        rating: 2.8636363,
      },
      {
        lie: false,
        id: 'g324',
        rating: 2.5,
        spoiler: 0,
      },
      {
        rating: 2.75,
        lie: false,
        id: 'g3401',
        spoiler: 1,
      },
      {
        spoiler: 2,
        rating: 1.9130435,
        id: 'g874',
        lie: false,
      },
      {
        spoiler: 0,
        id: 'g598',
        lie: false,
        rating: 2.6666667,
      },
      {
        spoiler: 0,
        rating: 2.8043478,
        lie: false,
        id: 'g215',
      },
      {
        spoiler: 2,
        rating: 2.6764705,
        id: 'g848',
        lie: false,
      },
      {
        id: 'g159',
        lie: false,
        rating: 2.6410255,
        spoiler: 0,
      },
      {
        rating: 2.75,
        id: 'g2765',
        lie: false,
        spoiler: 2,
      },
      {
        rating: 2.75,
        id: 'g692',
        lie: false,
        spoiler: 0,
      },
      {
        spoiler: 0,
        rating: 1.3571428,
        id: 'g771',
        lie: false,
      },
      {
        rating: 2.8444445,
        lie: false,
        id: 'g235',
        spoiler: 0,
      },
      {
        lie: false,
        id: 'g349',
        rating: 2.8,
        spoiler: 2,
      },
      {
        lie: false,
        id: 'g2390',
        rating: 2,
        spoiler: 1,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g1903',
        rating: 2.4285715,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g1154',
        rating: 2.7222223,
      },
      {
        spoiler: 0,
        rating: 1.4888889,
        id: 'g7',
        lie: false,
      },
      {
        spoiler: 1,
        rating: 1.4210526,
        lie: false,
        id: 'g163',
      },
      {
        spoiler: 0,
        id: 'g633',
        lie: false,
        rating: 1.25,
      },
      {
        rating: 2.8181818,
        lie: false,
        id: 'g424',
        spoiler: 0,
      },
      {
        id: 'g993',
        lie: false,
        rating: 2,
        spoiler: 0,
      },
      {
        spoiler: 1,
        id: 'g603',
        lie: false,
        rating: 0.09090909,
      },
      {
        lie: false,
        id: 'g1856',
        rating: 2.8333333,
        spoiler: 0,
      },
      {
        rating: 2.2,
        lie: false,
        id: 'g1398',
        spoiler: 1,
      },
      {
        spoiler: 0,
        rating: 2.4545455,
        lie: false,
        id: 'g1646',
      },
      {
        spoiler: 0,
        rating: 2.952381,
        lie: false,
        id: 'g146',
      },
      {
        rating: 2.8,
        id: 'g32',
        lie: false,
        spoiler: 0,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g3322',
        rating: 2.3333333,
      },
      {
        rating: 1.5,
        lie: false,
        id: 'g2147',
        spoiler: 2,
      },
      {
        spoiler: 0,
        id: 'g172',
        lie: false,
        rating: 1,
      },
      {
        rating: 2,
        id: 'g851',
        lie: false,
        spoiler: 0,
      },
      {
        spoiler: 2,
        lie: false,
        id: 'g252',
        rating: 3,
      },
      {
        spoiler: 1,
        rating: 2,
        lie: false,
        id: 'g1789',
      },
      {
        lie: false,
        id: 'g3137',
        rating: 2,
        spoiler: 1,
      },
      {
        spoiler: 0,
        rating: 2.6666667,
        lie: false,
        id: 'g135',
      },
      {
        spoiler: 0,
        rating: 2,
        id: 'g1759',
        lie: false,
      },
      {
        rating: 2.8,
        lie: false,
        id: 'g1059',
        spoiler: 1,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g323',
        rating: 2.7777777,
      },
      {
        id: 'g3005',
        lie: false,
        rating: 3,
        spoiler: 0,
      },
      {
        spoiler: 0,
        lie: false,
        id: 'g433',
        rating: 2.4848485,
      },
      {
        lie: false,
        id: 'g2542',
        rating: 1.8571428,
        spoiler: 0,
      },
      {
        rating: 1.4444444,
        lie: false,
        id: 'g824',
        spoiler: 1,
      },
      {
        spoiler: 0,
        rating: 3,
        lie: false,
        id: 'g1564',
      },
      {
        lie: false,
        id: 'g2',
        rating: 3,
        spoiler: 0,
      },
      {
        spoiler: 0,
        rating: 2,
        id: 'g1464',
        lie: false,
      },
      {
        rating: 2.7058823,
        id: 'g980',
        lie: false,
        spoiler: 2,
      },
      {
        lie: false,
        id: 'g96',
        rating: 1.7333333,
        spoiler: 1,
      },
      {
        rating: 2,
        id: 'g2133',
        lie: false,
        spoiler: 1,
      },
      {
        rating: 2.142857,
        lie: false,
        id: 'g2441',
        spoiler: 1,
      },
      {
        id: 'g160',
        lie: false,
        rating: 2.3777778,
        spoiler: 0,
      },
      {
        id: 'g112',
        lie: false,
        rating: 1.6969697,
        spoiler: 0,
      },
      {
        rating: 2.724138,
        lie: false,
        id: 'g1097',
        spoiler: 1,
      },
      {
        lie: false,
        id: 'g852',
        rating: 1.6666666,
        spoiler: 0,
      },
    ],
    languages: [
      'en',
      'es',
      'fr',
      'it',
      'ja',
      'ko',
      'pt-br',
      'ru',
      'tr',
      'uk',
      'zh-Hans',
      'zh-Hant',
    ],
    title: 'Umineko no Naku Koro ni',
    screenshots: [
      {
        thumbnail: 'https://s2.vndb.org/st/58/2658.jpg',
        thumbnail_dims: [136, 102],
      },
      {
        thumbnail: 'https://s2.vndb.org/st/60/2660.jpg',
        thumbnail_dims: [136, 102],
      },
      {
        thumbnail: 'https://s2.vndb.org/st/03/118303.jpg',
        thumbnail_dims: [136, 102],
      },
      {
        thumbnail_dims: [136, 77],
        thumbnail: 'https://s2.vndb.org/st/53/118553.jpg',
      },
      {
        thumbnail_dims: [136, 77],
        thumbnail: 'https://s2.vndb.org/st/74/118674.jpg',
      },
      {
        thumbnail_dims: [136, 77],
        thumbnail: 'https://s2.vndb.org/st/82/118682.jpg',
      },
      {
        thumbnail_dims: [136, 77],
        thumbnail: 'https://s2.vndb.org/st/00/119300.jpg',
      },
      {
        thumbnail: 'https://s2.vndb.org/st/02/119302.jpg',
        thumbnail_dims: [136, 77],
      },
      {
        thumbnail: 'https://s2.vndb.org/st/11/157311.jpg',
        thumbnail_dims: [136, 77],
      },
    ],
    rating: 88.3,
    popularity: 66.41,
  },
};
